### ISSUE TITLE
Explorer: Wrong hyperlink for smiles

### ISSUE THREAD

**Issue by stain** [openphacts/explorer2#18]
On https://explorer.openphacts.org/compounds?uri=http%3A%2F%2Fwww.conceptwiki.org%2Fconcept%2F13b4b707-8df0-4131-84b4-5433659e6ccf - the hyperlink for **SMILES** goes to https://explorer.openphacts.org/compounds/draw?smiles=undefined instead of the correct url using the URL encoded version of `CN1[C@H]2CC[C@@H]1[C@H]([C@H](C2)OC(=O)C3=CC=CC=C3)C(=O)OC` - is some thing with `=` going wrong here?

**Comment by danidi** [comment]
Even a very simple molecule as ethanol is returning undefined here: https://explorer.openphacts.org/compounds?uri=http%3A%2F%2Fwww.conceptwiki.org%2Fconcept%2F5d27706e-ed87-43f7-b621-fb6b12fc00c1. So it's not the = sign.

**Comment by ianwdunlop** [comment]
Probably caused by the Ember 1.11 upgrade. They changed how you pass params from the model to the template. I missed this one. Sorry.

**Comment by stain** [comment]
Thanks - already live on http://heater.cs.man.ac.uk:3001/compounds?uri=http%3A%2F%2Fwww.conceptwiki.org%2Fconcept%2F8a9f8f82-e5f2-4568-8387-4e48377de498 :)
